### ISSUE TITLE
Reply URL for MS Graph App

### ISSUE THREAD

**Issue by alexverboon** [Microsoft/MicrosoftGraphSecurity#11]
Hello, 

When I performed the App Registration in AzureAD I initially only used http://localhost:8080 as the reply URL, this resulted in the following error. 

> The reply address is missing, misconfigured, or does not match reply addresses configured for the application. Try out the resolution listed at https://docs.microsoft.com/azure/active-directory/application-sign-in-problem-federated-sso-gallery#the-reply-address-does-not-match-the-reply-addresses-configured-for-the-application. If you still see issues, contact the application owner or app admin.

Once I added **urn:ietf:wg:oauth:2.0:oob** I could authenticate and pull data in PowerShell as expected. 

Regards
Alex

**Comment by ani6gup** [comment]
Thank you @alexverboon! I added a clarification in the README.md to include this tip.
